### ISSUE TITLE
Add dynamic Cover Page for PDF Files

### ISSUE THREAD

**Issue by monsieuremre** [admin-shell-io/aas-specs-antora#12]
**Problem:**

As of now, the PDF files use static images on their cover page as the cover page itself. This is problematic on many levels. The content on the coverpage is not machine readable and cannot be parsed, this breaks many things functionality-wise, like in document searches or linking or editing or parsing for various purposes. Secondly, the pixel rate of the cover page is fixed. After a few compressions or viewing on different devices, it might look different and pixelated. The content on the cover page can not edited with ease dynamically. The cover page also poses several problems during auto generation alongside the html webpages, which do not have the static picture cover.

**Solution:**

It is possible and trivial to have the content of the cover page be integrated in the asciidoc file itself. It can be its own section and be formatted, and it will look way better and also be better in all ways for everyone.

**Additional things:**

You can observe one or more of these mentioned problems manifest themselves in some of the following documents.

* [Part 1](https://rwth-iat.github.io/aas-specs-antora/IDTA-01001/snapshot/draft-part-1-metamodel.pdf)

* [Part 2](https://rwth-iat.github.io/aas-specs-antora/IDTA-01002-3/snapshot/draft-part-2-api.pdf)

* [Part 3a](https://rwth-iat.github.io/aas-specs-antora/IDTA-01003-a/snapshot/draft-specification-asset-administration-shell-part-3a-iec61360.pdf)

* [Part 5](https://rwth-iat.github.io/aas-specs-antora/IDTA-01005/snapshot/draft-specification-asset-administration-shell-part-5-aasx-package-format.pdf)

**Comment by monsieuremre** [comment]
The following steps should be followed:

* Have a seperate logo image and declare it in the document headers
```
:title-logo-image: image:logo.png[]
```
* Have a IDTA blue background, and also the orange line that says specification. If desired, we can just drop the separate logo and have the logo incorperated in the background.
```
:title-page-background-image: image:title-bg.png[]
```

Now, the question is, how should I proceed to extract the necessary components. I can try to imidate the current cover page on my own in some image manipulation software.

Better would be, if we had the source images directly. Is there a way to acces the cover page image, with the logo and the specification line, but without the title and author and date? If you could provide me with that, I think it would be very easy to dynamically generate the cover pages.

**Comment by zrgt** [comment]
@monsieuremre, I've sent you the pages

**Comment by monsieuremre** [comment]
@zrgt I already reproduced the cover page dynamically successfully for single components. I'll push the changes after I implement this in the main repository. I'll see if we have to add the cover page background image to all the sources separately.

I can probably find a way to make it work whilst having the background in the main repository only. But in that case, if you want to produce the pdf file for a single component as a standalone, on its onw, not using this antora mechanism, it won't work.

Therefore, I suggest to add this background to all the sources.

Which one should I do? Add it to all components so that they can all be seperately generated if desired, or make it work only when they are generated here with antora?

**Comment by zrgt** [comment]
@monsieuremre We can add backgrounds to all sources

**Comment by monsieuremre** [comment]
Completed

**Comment by monsieuremre** [comment]
Logo can be extracted in higher resolution for better visuals. And also the title will be to the left instead of right.

**Comment by monsieuremre** [comment]
Now completed
