### ISSUE TITLE
Cross Reference Links in Source Documents

### ISSUE THREAD

**Issue by monsieuremre** [admin-shell-io/aas-specs-antora#14]
As Part 3a the latest document to be converted by us to asciidoc format, it also includes cross reference links within the same document. You can observe it [here](https://rwth-iat.github.io/aas-specs-antora/IDTA-01003-a/snapshot/IDTA-01003-a_Intro.html), where you can click on a mention of chapter 6 and you will be redirected to chapter 6. This behavior is not present in the other sources. And the conversion script that does the conversion whilst preserving the cross references is not mature enough to be deployed without manual interventions, by no means.

It is still possible however, to add this functionality to all of the documents. It will require some scripting, some use of the good old findutils for most things, and for some spots, also manual fixes. I think I can manage this in a reasonable time, if this feature is desired in all documents.

**Comment by monsieuremre** [comment]
Ping @zrgt

**Comment by zrgt** [comment]
Links are already manually fixed in the most of documents. We can close the issue.
