### ISSUE TITLE
Add line numbers in generated PDFs

### ISSUE THREAD

**Issue by zrgt** [admin-shell-io/aas-specs-antora#18]
For review reasons we need line numbers in generated PDFs.

Relevant issue: [fcf0c7850be0872e9a39da1e985b391385aa55dc](https://github.com/asciidoctor/asciidoctor-pdf/issues/636)

@monsieuremre please take a look, if it's possible to add line numbers in generated PDFs

**Comment by monsieuremre** [comment]
I have read through the documentation. Adding numbers to a block is possible and trivial.

Applying this to the whole document is not supported upstream.

A solution does not seem trivial, but possible. There is a link to an extended converter in the mentioned issue. Normally that would be trivial to call with something like ``` asciidoctor-pdf -r ./extended.rb file.adoc```

But we do not call the program directly. It is automated after site generation. I tried adding this option to the ```antora-assembler.yml``` file, but it does not work. It might be due the fact that it is called with bundle exec.

I will ask upstream for clarification on how we can use the extended converter with the antora extension.

**Comment by monsieuremre** [comment]
Impossible while using the default latest release.

Locally seems possible using the extended assembler. Does not seem trivial to enable the extended assembler in antora. Replacing the commands with the options does not work. Might be possible with the ruby specification file, if we somehow make it use the extended version as default. Not sure if possible.

Another option could be adding line numbers after the fact. This is tirvial to implement but will add complexity to the workflow. It may also not be reliable 100% all the time.

Asking upstream further. I will find out for sure if a direct solution is possible.

**Comment by zrgt** [comment]
@monsieuremre may be it is easier to create a Github Action for this and provide files additionally to normal PDFs.

**Comment by monsieuremre** [comment]
Completed
