### ISSUE TITLE
Broken layout of website for mobile versions

### ISSUE THREAD

**Issue by zrgt** [admin-shell-io/aas-specs-antora#19]
Currently the layout of the generated website for mobile pgones is broken. See the screenshot.

![grafik](https://github.com/admin-shell-io/aas-specs-antora/assets/56840636/3dedec44-f727-4e06-9998-c8b72e2de4ae)

I guess it happens because of "Download" button.

**Comment by monsieuremre** [comment]
Fixed with https://github.com/admin-shell-io/aas-specs-antora-ui/commits/v0.4.1/
