### ISSUE TITLE
Update images in `index.adoc` when images for V3.1 available

### ISSUE THREAD

**Issue by zrgt** [admin-shell-io/aas-specs-antora#6]
Currently images for V3.0 are used to show the available docs. We should update them when the new images for V3.1 are published.

**Comment by monsieuremre** [comment]
We are barely ın control in any of the source repositories now. When the images change in sources, they should change here.

If you meant the images that are in the main page here in this repository, these are just the cover pages. I will update those accordingly when the next versions releases, but I thought we were planning to replace having images for cover pages with having these coverpages be generated dynamically like the rest of the content. As so discussed in https://github.com/rwth-iat/aas-specs-antora/issues/12.

**Comment by zrgt** [comment]
Solved in fcf0c7850be0872e9a39da1e985b391385aa55dc
